### ISSUE TITLE
Wrong modifier on background colors

### ISSUE THREAD

**Issue by krokofant** [roperzh/tachyons-cheatsheet#13]
[official docs](http://tachyons.io/docs/themes/skins/)
[source](https://github.com/tachyons-css/tachyons/blob/master/src/_skins.css)

`--color-name` should be `-color-name`

```css
.black { color: #000000 }
.bg-light-silver { background-color: #AAAAAA }
```
